// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGNAPvQGjQxmF71yeOhpfkzxHxhlT0HWU',
    appId: '1:268441347443:web:39766930b157ef4c209106',
    messagingSenderId: '268441347443',
    projectId: 'wallpaper-ae985',
    authDomain: 'wallpaper-ae985.firebaseapp.com',
    storageBucket: 'wallpaper-ae985.firebasestorage.app',
    measurementId: 'G-WHYJ5JL8DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABGlXQPa0Q_Mt6uehuBiQRF79RHZ65OUM',
    appId: '1:268441347443:android:a986b870a517d4fa209106',
    messagingSenderId: '268441347443',
    projectId: 'wallpaper-ae985',
    storageBucket: 'wallpaper-ae985.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Z8bKeVYmrAIvVzGL3G4q9Hfm4lz7ZSI',
    appId: '1:268441347443:ios:c3cf60e842632f6d209106',
    messagingSenderId: '268441347443',
    projectId: 'wallpaper-ae985',
    storageBucket: 'wallpaper-ae985.firebasestorage.app',
    iosBundleId: 'com.example.wallpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Z8bKeVYmrAIvVzGL3G4q9Hfm4lz7ZSI',
    appId: '1:268441347443:ios:c3cf60e842632f6d209106',
    messagingSenderId: '268441347443',
    projectId: 'wallpaper-ae985',
    storageBucket: 'wallpaper-ae985.firebasestorage.app',
    iosBundleId: 'com.example.wallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGNAPvQGjQxmF71yeOhpfkzxHxhlT0HWU',
    appId: '1:268441347443:web:ab8a63c3472519bd209106',
    messagingSenderId: '268441347443',
    projectId: 'wallpaper-ae985',
    authDomain: 'wallpaper-ae985.firebaseapp.com',
    storageBucket: 'wallpaper-ae985.firebasestorage.app',
    measurementId: 'G-6QPNYZE8N1',
  );
}
